// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTbfEKOF1DnNX_tEWkc1v6LH5NnoBUpq4',
    appId: '1:197525165172:web:ff97d1acac3f1b3c2f6d21',
    messagingSenderId: '197525165172',
    projectId: 'ruralgo-204eb',
    authDomain: 'ruralgo-204eb.firebaseapp.com',
    storageBucket: 'ruralgo-204eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SfGPzUUY2S2lEtANqrPFW3DdxXU3Msg',
    appId: '1:197525165172:android:c7164dd505534f442f6d21',
    messagingSenderId: '197525165172',
    projectId: 'ruralgo-204eb',
    storageBucket: 'ruralgo-204eb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTbfEKOF1DnNX_tEWkc1v6LH5NnoBUpq4',
    appId: '1:197525165172:web:e951be867c480f3b2f6d21',
    messagingSenderId: '197525165172',
    projectId: 'ruralgo-204eb',
    authDomain: 'ruralgo-204eb.firebaseapp.com',
    storageBucket: 'ruralgo-204eb.firebasestorage.app',
  );
}
